import { writable, readable } from 'svelte/store';

import whitePawn from '../public/assets/svg/Chess_plt45.svg';
import whiteKnight from '../public/assets/svg/Chess_nlt45.svg';
import whiteBishop from '../public/assets/svg/Chess_blt45.svg';
import whiteRook from '../public/assets/svg/Chess_rlt45.svg';
import whiteQueen from '../public/assets/svg/Chess_qlt45.svg';
import whiteKing from '../public/assets/svg/Chess_klt45.svg';

import blackPawn from '../public/assets/svg/Chess_pdt45.svg';
import blackKnight from '../public/assets/svg/Chess_ndt45.svg';
import blackBishop from '../public/assets/svg/Chess_bdt45.svg';
import blackRook from '../public/assets/svg/Chess_rdt45.svg';
import blackQueen from '../public/assets/svg/Chess_qdt45.svg';
import blackKing from '../public/assets/svg/Chess_kdt45.svg';

export const piecePlacedSFX = new Audio('assets/sfx/chess.mp3');

export const board = writable([
    [
        {
            piece: 'Black Rook 1',
            type: 'rook',
            row: 0,
            column: 0,
            taken: false,
            image: blackRook,
        },
        {
            piece: 'Black Knight 1',
            type: 'knight',
            row: 0,
            column: 1,
            taken: false,
            image: blackKnight,
        },
        {
            piece: 'Black Bishop 1',
            type: 'bishop',
            row: 0,
            column: 2,
            taken: false,
            image: blackBishop,
        },
        {
            piece: 'Black Queen',
            type: 'queen',
            row: 0,
            column: 3,
            taken: false,
            image: blackQueen,
        },
        {
            piece: 'Black King',
            type: 'king',
            row: 0,
            column: 4,
            taken: false,
            image: blackKing,
        },
        {
            piece: 'Black Bishop 2',
            type: 'bishop',
            row: 0,
            column: 5,
            taken: false,
            image: blackBishop,
        },
        {
            piece: 'Black Knight 2',
            type: 'knight',
            row: 0,
            column: 6,
            taken: false,
            image: blackKnight,
        },
        {
            piece: 'Black Rook 2',
            type: 'rook',
            row: 0,
            column: 7,
            taken: false,
            image: blackRook,
        },
    ],
    [
        {
            piece: 'Black Pawn 1',
            type: 'pawn',
            row: 1,
            column: 0,
            taken: false,
            image: blackPawn,
        },
        {
            piece: 'Black Pawn 2',
            type: 'pawn',
            row: 1,
            column: 1,
            taken: false,
            image: blackPawn,
        },
        {
            piece: 'Black Pawn 3',
            type: 'pawn',
            row: 1,
            column: 2,
            taken: false,
            image: blackPawn,
        },
        {
            piece: 'Black Pawn 4',
            type: 'pawn',
            row: 1,
            column: 3,
            taken: false,
            image: blackPawn,
        },
        {
            piece: 'Black Pawn 5',
            type: 'pawn',
            row: 1,
            column: 4,
            taken: false,
            image: blackPawn,
        },
        {
            piece: 'Black Pawn 6',
            type: 'pawn',
            row: 1,
            column: 5,
            taken: false,
            image: blackPawn,
        },
        {
            piece: 'Black Pawn 7',
            type: 'pawn',
            row: 1,
            column: 6,
            taken: false,
            image: blackPawn,
        },
        {
            piece: 'Black Pawn 8',
            type: 'pawn',
            row: 1,
            column: 7,
            taken: false,
            image: blackPawn,
        },
    ],
    [undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined],
    [undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined],
    [undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined],
    [undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined],
    [
        {
            piece: 'White Pawn 1',
            type: 'pawn',
            row: 6,
            column: 0,
            taken: false,
            image: whitePawn,
        },
        {
            piece: 'White Pawn 2',
            type: 'pawn',
            row: 6,
            column: 1,
            taken: false,
            image: whitePawn,
        },
        {
            piece: 'White Pawn 3',
            type: 'pawn',
            row: 6,
            column: 2,
            taken: false,
            image: whitePawn,
        },
        {
            piece: 'White Pawn 4',
            type: 'pawn',
            row: 6,
            column: 3,
            taken: false,
            image: whitePawn,
        },
        {
            piece: 'White Pawn 5',
            type: 'pawn',
            row: 6,
            column: 4,
            taken: false,
            image: whitePawn,
        },
        {
            piece: 'White Pawn 6',
            type: 'pawn',
            row: 6,
            column: 5,
            taken: false,
            image: whitePawn,
        },
        {
            piece: 'White Pawn 7',
            type: 'pawn',
            row: 6,
            column: 6,
            taken: false,
            image: whitePawn,
        },
        {
            piece: 'White Pawn 8',
            type: 'pawn',
            row: 6,
            column: 7,
            taken: false,
            image: whitePawn,
        },
    ],
    [
        {
            piece: 'White Rook 1',
            type: 'rook',
            row: 7,
            column: 0,
            taken: false,
            image: whiteRook,
        },
        {
            piece: 'White Knight 1',
            type: 'knight',
            row: 7,
            column: 1,
            taken: false,
            image: whiteKnight,
        },
        {
            piece: 'White Bishop 1',
            type: 'bishop',
            row: 7,
            column: 2,
            taken: false,
            image: whiteBishop,
        },
        {
            piece: 'White Queen',
            type: 'queen',
            row: 7,
            column: 3,
            taken: false,
            image: whiteQueen,
        },
        {
            piece: 'White King',
            type: 'king',
            row: 7,
            column: 4,
            taken: false,
            image: whiteKing,
        },
        {
            piece: 'White Bishop 2',
            type: 'bishop',
            row: 7,
            column: 5,
            taken: false,
            image: whiteBishop,
        },
        {
            piece: 'White Knight 2',
            type: 'knight',
            row: 7,
            column: 6,
            taken: false,
            image: whiteKnight,
        },
        {
            piece: 'White Rook 2',
            type: 'rook',
            row: 7,
            column: 7,
            taken: false,
            image: whiteRook,
        },
    ],
]);
